import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import "../globals.css";

export const metadata = {
  title: "AccessiNor AS",
  description: "Generated by AccessiNor AS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full">
        <main>
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
